//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia.App_Class.BL
{


	public partial class Veh_BLTipoVehiculo
	{

		/// <summary>
		/// control form1.
		/// </summary>
		/// <remarks>
		/// Campo generado automáticamente.
		/// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlForm form1;
	}
}
