#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_A443E1_Farmacia")]
	public partial class DataFarmaciaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public DataFarmaciaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BD"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataFarmaciaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataFarmaciaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataFarmaciaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataFarmaciaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="seg.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDUsuario;
		
		private System.Nullable<int> _IDColaborador;
		
		private string _Usuario1;
		
		private string _Clave;
		
		private bool _Bloqueado;
		
		private System.Nullable<System.DateTime> _FechaBloqueo;
		
		private System.Nullable<int> _NumIntentoFallidoLogin;
		
		private System.Nullable<System.DateTime> _FechaUltimoIntentoLogin;
		
		private System.Nullable<System.DateTime> _FechaBajaInactividad;
		
		private System.Nullable<bool> _CambiarClave;
		
		private System.Nullable<int> _NumIntentoRecuperarClave;
		
		private System.Nullable<System.DateTime> _FechaUltimoIntentoRecuperarClave;
		
		private bool _Estado;
		
		private System.Nullable<int> _IDUsuarioCreacion;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
		private System.Nullable<int> _IDUsuarioModificacion;
		
		private System.Nullable<System.DateTime> _FechaModificacion;
		
		private string _EmailUser;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUsuarioChanging(int value);
    partial void OnIDUsuarioChanged();
    partial void OnIDColaboradorChanging(System.Nullable<int> value);
    partial void OnIDColaboradorChanged();
    partial void OnUsuario1Changing(string value);
    partial void OnUsuario1Changed();
    partial void OnClaveChanging(string value);
    partial void OnClaveChanged();
    partial void OnBloqueadoChanging(bool value);
    partial void OnBloqueadoChanged();
    partial void OnFechaBloqueoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaBloqueoChanged();
    partial void OnNumIntentoFallidoLoginChanging(System.Nullable<int> value);
    partial void OnNumIntentoFallidoLoginChanged();
    partial void OnFechaUltimoIntentoLoginChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaUltimoIntentoLoginChanged();
    partial void OnFechaBajaInactividadChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaBajaInactividadChanged();
    partial void OnCambiarClaveChanging(System.Nullable<bool> value);
    partial void OnCambiarClaveChanged();
    partial void OnNumIntentoRecuperarClaveChanging(System.Nullable<int> value);
    partial void OnNumIntentoRecuperarClaveChanged();
    partial void OnFechaUltimoIntentoRecuperarClaveChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaUltimoIntentoRecuperarClaveChanged();
    partial void OnEstadoChanging(bool value);
    partial void OnEstadoChanged();
    partial void OnIDUsuarioCreacionChanging(System.Nullable<int> value);
    partial void OnIDUsuarioCreacionChanged();
    partial void OnFechaCreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCreacionChanged();
    partial void OnIDUsuarioModificacionChanging(System.Nullable<int> value);
    partial void OnIDUsuarioModificacionChanged();
    partial void OnFechaModificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaModificacionChanged();
    partial void OnEmailUserChanging(string value);
    partial void OnEmailUserChanged();
    #endregion
		
		public Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDUsuario
		{
			get
			{
				return this._IDUsuario;
			}
			set
			{
				if ((this._IDUsuario != value))
				{
					this.OnIDUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IDUsuario = value;
					this.SendPropertyChanged("IDUsuario");
					this.OnIDUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDColaborador", DbType="Int")]
		public System.Nullable<int> IDColaborador
		{
			get
			{
				return this._IDColaborador;
			}
			set
			{
				if ((this._IDColaborador != value))
				{
					this.OnIDColaboradorChanging(value);
					this.SendPropertyChanging();
					this._IDColaborador = value;
					this.SendPropertyChanged("IDColaborador");
					this.OnIDColaboradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Usuario", Storage="_Usuario1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usuario1
		{
			get
			{
				return this._Usuario1;
			}
			set
			{
				if ((this._Usuario1 != value))
				{
					this.OnUsuario1Changing(value);
					this.SendPropertyChanging();
					this._Usuario1 = value;
					this.SendPropertyChanged("Usuario1");
					this.OnUsuario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this.OnClaveChanging(value);
					this.SendPropertyChanging();
					this._Clave = value;
					this.SendPropertyChanged("Clave");
					this.OnClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bloqueado", DbType="Bit NOT NULL")]
		public bool Bloqueado
		{
			get
			{
				return this._Bloqueado;
			}
			set
			{
				if ((this._Bloqueado != value))
				{
					this.OnBloqueadoChanging(value);
					this.SendPropertyChanging();
					this._Bloqueado = value;
					this.SendPropertyChanged("Bloqueado");
					this.OnBloqueadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaBloqueo", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaBloqueo
		{
			get
			{
				return this._FechaBloqueo;
			}
			set
			{
				if ((this._FechaBloqueo != value))
				{
					this.OnFechaBloqueoChanging(value);
					this.SendPropertyChanging();
					this._FechaBloqueo = value;
					this.SendPropertyChanged("FechaBloqueo");
					this.OnFechaBloqueoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumIntentoFallidoLogin", DbType="Int")]
		public System.Nullable<int> NumIntentoFallidoLogin
		{
			get
			{
				return this._NumIntentoFallidoLogin;
			}
			set
			{
				if ((this._NumIntentoFallidoLogin != value))
				{
					this.OnNumIntentoFallidoLoginChanging(value);
					this.SendPropertyChanging();
					this._NumIntentoFallidoLogin = value;
					this.SendPropertyChanged("NumIntentoFallidoLogin");
					this.OnNumIntentoFallidoLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUltimoIntentoLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaUltimoIntentoLogin
		{
			get
			{
				return this._FechaUltimoIntentoLogin;
			}
			set
			{
				if ((this._FechaUltimoIntentoLogin != value))
				{
					this.OnFechaUltimoIntentoLoginChanging(value);
					this.SendPropertyChanging();
					this._FechaUltimoIntentoLogin = value;
					this.SendPropertyChanged("FechaUltimoIntentoLogin");
					this.OnFechaUltimoIntentoLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaBajaInactividad", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaBajaInactividad
		{
			get
			{
				return this._FechaBajaInactividad;
			}
			set
			{
				if ((this._FechaBajaInactividad != value))
				{
					this.OnFechaBajaInactividadChanging(value);
					this.SendPropertyChanging();
					this._FechaBajaInactividad = value;
					this.SendPropertyChanged("FechaBajaInactividad");
					this.OnFechaBajaInactividadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CambiarClave", DbType="Bit")]
		public System.Nullable<bool> CambiarClave
		{
			get
			{
				return this._CambiarClave;
			}
			set
			{
				if ((this._CambiarClave != value))
				{
					this.OnCambiarClaveChanging(value);
					this.SendPropertyChanging();
					this._CambiarClave = value;
					this.SendPropertyChanged("CambiarClave");
					this.OnCambiarClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumIntentoRecuperarClave", DbType="Int")]
		public System.Nullable<int> NumIntentoRecuperarClave
		{
			get
			{
				return this._NumIntentoRecuperarClave;
			}
			set
			{
				if ((this._NumIntentoRecuperarClave != value))
				{
					this.OnNumIntentoRecuperarClaveChanging(value);
					this.SendPropertyChanging();
					this._NumIntentoRecuperarClave = value;
					this.SendPropertyChanged("NumIntentoRecuperarClave");
					this.OnNumIntentoRecuperarClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUltimoIntentoRecuperarClave", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaUltimoIntentoRecuperarClave
		{
			get
			{
				return this._FechaUltimoIntentoRecuperarClave;
			}
			set
			{
				if ((this._FechaUltimoIntentoRecuperarClave != value))
				{
					this.OnFechaUltimoIntentoRecuperarClaveChanging(value);
					this.SendPropertyChanging();
					this._FechaUltimoIntentoRecuperarClave = value;
					this.SendPropertyChanged("FechaUltimoIntentoRecuperarClave");
					this.OnFechaUltimoIntentoRecuperarClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUsuarioCreacion", DbType="Int")]
		public System.Nullable<int> IDUsuarioCreacion
		{
			get
			{
				return this._IDUsuarioCreacion;
			}
			set
			{
				if ((this._IDUsuarioCreacion != value))
				{
					this.OnIDUsuarioCreacionChanging(value);
					this.SendPropertyChanging();
					this._IDUsuarioCreacion = value;
					this.SendPropertyChanged("IDUsuarioCreacion");
					this.OnIDUsuarioCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUsuarioModificacion", DbType="Int")]
		public System.Nullable<int> IDUsuarioModificacion
		{
			get
			{
				return this._IDUsuarioModificacion;
			}
			set
			{
				if ((this._IDUsuarioModificacion != value))
				{
					this.OnIDUsuarioModificacionChanging(value);
					this.SendPropertyChanging();
					this._IDUsuarioModificacion = value;
					this.SendPropertyChanged("IDUsuarioModificacion");
					this.OnIDUsuarioModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this.OnFechaModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaModificacion = value;
					this.SendPropertyChanged("FechaModificacion");
					this.OnFechaModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailUser", DbType="VarChar(100)")]
		public string EmailUser
		{
			get
			{
				return this._EmailUser;
			}
			set
			{
				if ((this._EmailUser != value))
				{
					this.OnEmailUserChanging(value);
					this.SendPropertyChanging();
					this._EmailUser = value;
					this.SendPropertyChanged("EmailUser");
					this.OnEmailUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
